config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("gramaverde.core.urls", namespace="core")),
]

if settings.DEBUG:
    urlpatterns = (
        urlpatterns
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

gramaverde/core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
]

gramaverde/core/views.py
from django.views import generic


class Index(generic.TemplateView):
    template_name = "pages/index.html"


index = Index.as_view()

templates/templates/base.html
{% load i18n static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" dir="{{ LANGUAGE_BIDI|yesno:'rtl,ltr,auto' }}" data-bs-theme="light">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>{% block title %}{% endblock title %} / Grama Verde</title>
    {# ===== Favicons ===== #}
    <link rel="shortcut icon" href="https://res.cloudinary.com/dejjtt8yt/image/upload/v1672892961/grama%20verde/favicon_rd2vut.ico" type="image/x-icon">
    {# ===== Author ===== #}
    <meta name="author" content="Grama Verde">
    {# ===== Description ===== #}
    <meta name="description" content="News portal about the world of comics, manga, anime and everything else">
    {# ===== Keywords ===== #}
    <meta name="keywords" content="comics, mangas, animes, movies, games">
    {# ===== Bootstrap CSS ===== #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    {# ===== Font Awesome ===== #}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {# ===== Static CSS ===== #}
    <link rel="stylesheet" href="{% block stylesheet %}{% static "css/base.css" %}{% endblock %}">
    {# ===== Bootstrap JS ===== #}
    <script deref src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script deref src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
    {# ===== Static JS ===== #}
    <script deref src="{% block script %}{% static "js/script.js" %}{% endblock script %}"></script>
  </head>
  <body>
    {% block content %}{% endblock content %}
  </body>
</html>

templates/templates/pages/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}


{% block content %}
<header class="py-3">
  <div class="container-xl">
    <div class="d-flex align-items-center  justify-content-between justify-content-md-center">
      <h1><a href="{% url 'core:index' %}" class="m-0">
        <img src="https://res.cloudinary.com/dejjtt8yt/image/upload/v1672892961/grama%20verde/logo_s8ds6a.png" alt="logo" width="128" height="48">
      </a></h1>
      <div>
        <button type="button" class="btn btn-outline-secondary d-md-none" data-bs-toggle="modal" data-bs-target="#modalSearch">
          <i class="fa-solid fa-magnifying-glass"></i>
        </button>
        <button class="btn btn-outline-secondary d-md-none" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavMenu" aria-controls="offcanvasNavMenu">
          <i class="fa-solid fa-bars"></i>
        </button>
      </div>
    </div>
  </div>
</header>

<div class="container-xl border-top border-bottom d-none d-md-block">
  <nav class="d-flex justify-content-center align-items-center gap-2">
    <a href="" class="btn">Comics</a>
    <a href="" class="btn">Mangas</a>
    <a href="" class="btn">Animes</a>
    <a href="" class="btn">Movies</a>
    <a href="" class="btn">Games</a>
  </nav>
</div>

{# Modal Search #}
<div class="modal fade" id="modalSearch" tabindex="-1" aria-labelledby="modalSearchLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body">
        <form action="" method="post">
          {% csrf_token %}
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search" aria-label="Recipient's username" aria-describedby="basic-addon2">
            <button type="submit" class="input-group-text" id="basic-addon2">
              <i class="fa-solid fa-magnifying-glass"></i>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{# OffCanvas Nav Menu #}
<section class="offcanvas offcanvas offcanvas-end w-100 m-0 p-0" tabindex="-1" id="offcanvasNavMenu" aria-labelledby="offcanvasNavMenuLabel">
  <div class="container-xl h-100">
    <header class="offcanvas-header px-0 py-3">
      <h5 class="offcanvas-title" id="offcanvasNavMenuLabel">
        <img src="https://res.cloudinary.com/dejjtt8yt/image/upload/v1672892961/grama%20verde/logo_s8ds6a.png" alt="logo" width="128" height="48">
      </h5>
      <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="offcanvas" aria-label="Close">
        <i class="fa-solid fa-xmark"></i>
      </button>
    </header>
    <main class="offcanvas-body h-75 my-5">
      <nav class="d-flex flex-column justify-content-between align-content-center h-100">
        <a href="" class="btn">Comics</a>
        <a href="" class="btn">Mangas</a>
        <a href="" class="btn">Animes</a>
        <a href="" class="btn">Movies</a>
        <a href="" class="btn">Games</a>
      </nav>
    </main>
  </div>
</section>
{% endblock content %}